// flow-typed signature: 26bfa53c55668fa5e8200c0d7643816f
// flow-typed version: <<STUB>>/react-habitat-redux_v^2.0.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-habitat-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-habitat-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-habitat-redux/dist/react-habitat-redux' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/dist/react-habitat-redux.min' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/karma.conf' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/lib/index' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/lib/ReduxDomFactory' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/src/index' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/src/ReduxDomFactory' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/tests/Bootstrapper.spec' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/tests/fixtures/MockActions' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/tests/fixtures/MockContainer' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/tests/fixtures/mockReducer' {
  declare module.exports: any;
}

declare module 'react-habitat-redux/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-habitat-redux/dist/react-habitat-redux.js' {
  declare module.exports: $Exports<'react-habitat-redux/dist/react-habitat-redux'>;
}
declare module 'react-habitat-redux/dist/react-habitat-redux.min.js' {
  declare module.exports: $Exports<'react-habitat-redux/dist/react-habitat-redux.min'>;
}
declare module 'react-habitat-redux/karma.conf.js' {
  declare module.exports: $Exports<'react-habitat-redux/karma.conf'>;
}
declare module 'react-habitat-redux/lib/index.js' {
  declare module.exports: $Exports<'react-habitat-redux/lib/index'>;
}
declare module 'react-habitat-redux/lib/ReduxDomFactory.js' {
  declare module.exports: $Exports<'react-habitat-redux/lib/ReduxDomFactory'>;
}
declare module 'react-habitat-redux/src/index.js' {
  declare module.exports: $Exports<'react-habitat-redux/src/index'>;
}
declare module 'react-habitat-redux/src/ReduxDomFactory.js' {
  declare module.exports: $Exports<'react-habitat-redux/src/ReduxDomFactory'>;
}
declare module 'react-habitat-redux/tests/Bootstrapper.spec.js' {
  declare module.exports: $Exports<'react-habitat-redux/tests/Bootstrapper.spec'>;
}
declare module 'react-habitat-redux/tests/fixtures/MockActions.js' {
  declare module.exports: $Exports<'react-habitat-redux/tests/fixtures/MockActions'>;
}
declare module 'react-habitat-redux/tests/fixtures/MockContainer.jsx' {
  declare module.exports: $Exports<'react-habitat-redux/tests/fixtures/MockContainer'>;
}
declare module 'react-habitat-redux/tests/fixtures/mockReducer.js' {
  declare module.exports: $Exports<'react-habitat-redux/tests/fixtures/mockReducer'>;
}
declare module 'react-habitat-redux/webpack.config.js' {
  declare module.exports: $Exports<'react-habitat-redux/webpack.config'>;
}
