// flow-typed signature: a486d00f4fa4b87c279edbcd02959431
// flow-typed version: <<STUB>>/react-habitat_v^1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-habitat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-habitat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-habitat/dist/react-habitat' {
  declare module.exports: any;
}

declare module 'react-habitat/dist/react-habitat.min' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/Bootstrapper' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/builder/ContainerBuilder' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/classic/createBootstrapper' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/classic/index' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/Container' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/factories/ReactDomFactory' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/Habitat' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/index' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/Logger' {
  declare module.exports: any;
}

declare module 'react-habitat/lib/Registration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-habitat/dist/react-habitat.js' {
  declare module.exports: $Exports<'react-habitat/dist/react-habitat'>;
}
declare module 'react-habitat/dist/react-habitat.min.js' {
  declare module.exports: $Exports<'react-habitat/dist/react-habitat.min'>;
}
declare module 'react-habitat/lib/Bootstrapper.js' {
  declare module.exports: $Exports<'react-habitat/lib/Bootstrapper'>;
}
declare module 'react-habitat/lib/builder/ContainerBuilder.js' {
  declare module.exports: $Exports<'react-habitat/lib/builder/ContainerBuilder'>;
}
declare module 'react-habitat/lib/classic/createBootstrapper.js' {
  declare module.exports: $Exports<'react-habitat/lib/classic/createBootstrapper'>;
}
declare module 'react-habitat/lib/classic/index.js' {
  declare module.exports: $Exports<'react-habitat/lib/classic/index'>;
}
declare module 'react-habitat/lib/Container.js' {
  declare module.exports: $Exports<'react-habitat/lib/Container'>;
}
declare module 'react-habitat/lib/factories/ReactDomFactory.js' {
  declare module.exports: $Exports<'react-habitat/lib/factories/ReactDomFactory'>;
}
declare module 'react-habitat/lib/Habitat.js' {
  declare module.exports: $Exports<'react-habitat/lib/Habitat'>;
}
declare module 'react-habitat/lib/index.js' {
  declare module.exports: $Exports<'react-habitat/lib/index'>;
}
declare module 'react-habitat/lib/Logger.js' {
  declare module.exports: $Exports<'react-habitat/lib/Logger'>;
}
declare module 'react-habitat/lib/Registration.js' {
  declare module.exports: $Exports<'react-habitat/lib/Registration'>;
}
