package fi.weasel.commitment2050.commitmentanalysis.model;

public enum CAResultType {
    TOTAL_CARBON_REDUCED_KG,
    COUNT_APPROVED_COMMITMENTS_FROM_LIFESTYLE_TEST,
    COUNT_APPROVED_COMMITMENTS_PERSONAL,
    COUNT_APPROVED_COMMITMENTS_ORGANIZATION,
    COUNT_APPROVED_COMMITMENTS_NUTRITION,
    COUNT_APPROVED_GREEN_DEAL_TOTAL,
    COUNT_APPROVED_GREEN_DEAL_OIL_INDUSTRY,
    COUNT_APPROVED_GREEN_DEAL_AUTOMOTIVE_INDUSTRY,
    COUNT_APPROVED_GREEN_DEAL_WORK_MACHINE,
    COUNT_APPROVED_GREEN_DEAL_PLASTIC_BAG,
    COUNT_APPROVED_GREEN_DEAL_DEMOLITION,
    COUNT_PERSONAL_COMMITMENTS_WILL_CHOOSE_LOCAL_FOOD,
    COUNT_PERSONAL_COMMITMENTS_WILL_DO_VEGAN_CHALLENGE,
    COUNT_PERSONAL_COMMITMENTS_WILL_REPAIR_GOOD_PRODUCTS
    //AVERAGE_REDUCTION_PERCENTAGE
}
