/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fi.weasel.commitment2050.commitmentanalysis.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Commitment service. Represents a row in the &quot;CA_Commitment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.weasel.commitment2050.commitmentanalysis.model.impl.CommitmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.weasel.commitment2050.commitmentanalysis.model.impl.CommitmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Commitment
 * @see fi.weasel.commitment2050.commitmentanalysis.model.impl.CommitmentImpl
 * @see fi.weasel.commitment2050.commitmentanalysis.model.impl.CommitmentModelImpl
 * @generated
 */
@ProviderType
public interface CommitmentModel extends BaseModel<Commitment>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commitment model instance should use the {@link Commitment} interface instead.
	 */

	/**
	 * Returns the primary key of this commitment.
	 *
	 * @return the primary key of this commitment
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this commitment.
	 *
	 * @param primaryKey the primary key of this commitment
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the commitment ID of this commitment.
	 *
	 * @return the commitment ID of this commitment
	 */
	@AutoEscape
	public String getCommitmentId();

	/**
	 * Sets the commitment ID of this commitment.
	 *
	 * @param commitmentId the commitment ID of this commitment
	 */
	public void setCommitmentId(String commitmentId);

	/**
	 * Returns the group ID of this commitment.
	 *
	 * @return the group ID of this commitment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this commitment.
	 *
	 * @param groupId the group ID of this commitment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this commitment.
	 *
	 * @return the company ID of this commitment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commitment.
	 *
	 * @param companyId the company ID of this commitment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the organization ID of this commitment.
	 *
	 * @return the organization ID of this commitment
	 */
	@AutoEscape
	public String getOrganizationId();

	/**
	 * Sets the organization ID of this commitment.
	 *
	 * @param organizationId the organization ID of this commitment
	 */
	public void setOrganizationId(String organizationId);

	/**
	 * Returns the user ID of this commitment.
	 *
	 * @return the user ID of this commitment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commitment.
	 *
	 * @param userId the user ID of this commitment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commitment.
	 *
	 * @return the user uuid of this commitment
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commitment.
	 *
	 * @param userUuid the user uuid of this commitment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commitment.
	 *
	 * @return the user name of this commitment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commitment.
	 *
	 * @param userName the user name of this commitment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commitment.
	 *
	 * @return the create date of this commitment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commitment.
	 *
	 * @param createDate the create date of this commitment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commitment.
	 *
	 * @return the modified date of this commitment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commitment.
	 *
	 * @param modifiedDate the modified date of this commitment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title fi of this commitment.
	 *
	 * @return the title fi of this commitment
	 */
	@AutoEscape
	public String getTitleFI();

	/**
	 * Sets the title fi of this commitment.
	 *
	 * @param titleFI the title fi of this commitment
	 */
	public void setTitleFI(String titleFI);

	/**
	 * Returns the title en of this commitment.
	 *
	 * @return the title en of this commitment
	 */
	@AutoEscape
	public String getTitleEN();

	/**
	 * Sets the title en of this commitment.
	 *
	 * @param titleEN the title en of this commitment
	 */
	public void setTitleEN(String titleEN);

	/**
	 * Returns the title sv of this commitment.
	 *
	 * @return the title sv of this commitment
	 */
	@AutoEscape
	public String getTitleSV();

	/**
	 * Sets the title sv of this commitment.
	 *
	 * @param titleSV the title sv of this commitment
	 */
	public void setTitleSV(String titleSV);

	/**
	 * Returns the start date of this commitment.
	 *
	 * @return the start date of this commitment
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this commitment.
	 *
	 * @param startDate the start date of this commitment
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this commitment.
	 *
	 * @return the end date of this commitment
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this commitment.
	 *
	 * @param endDate the end date of this commitment
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the updated of this commitment.
	 *
	 * @return the updated of this commitment
	 */
	public Date getUpdated();

	/**
	 * Sets the updated of this commitment.
	 *
	 * @param updated the updated of this commitment
	 */
	public void setUpdated(Date updated);

	/**
	 * Returns the created of this commitment.
	 *
	 * @return the created of this commitment
	 */
	public Date getCreated();

	/**
	 * Sets the created of this commitment.
	 *
	 * @param created the created of this commitment
	 */
	public void setCreated(Date created);

	/**
	 * Returns the innovation fi of this commitment.
	 *
	 * @return the innovation fi of this commitment
	 */
	@AutoEscape
	public String getInnovationFI();

	/**
	 * Sets the innovation fi of this commitment.
	 *
	 * @param innovationFI the innovation fi of this commitment
	 */
	public void setInnovationFI(String innovationFI);

	/**
	 * Returns the innovation en of this commitment.
	 *
	 * @return the innovation en of this commitment
	 */
	@AutoEscape
	public String getInnovationEN();

	/**
	 * Sets the innovation en of this commitment.
	 *
	 * @param innovationEN the innovation en of this commitment
	 */
	public void setInnovationEN(String innovationEN);

	/**
	 * Returns the innovation sv of this commitment.
	 *
	 * @return the innovation sv of this commitment
	 */
	@AutoEscape
	public String getInnovationSV();

	/**
	 * Sets the innovation sv of this commitment.
	 *
	 * @param innovationSV the innovation sv of this commitment
	 */
	public void setInnovationSV(String innovationSV);

	/**
	 * Returns the background information fi of this commitment.
	 *
	 * @return the background information fi of this commitment
	 */
	@AutoEscape
	public String getBackgroundInformationFI();

	/**
	 * Sets the background information fi of this commitment.
	 *
	 * @param backgroundInformationFI the background information fi of this commitment
	 */
	public void setBackgroundInformationFI(String backgroundInformationFI);

	/**
	 * Returns the background information en of this commitment.
	 *
	 * @return the background information en of this commitment
	 */
	@AutoEscape
	public String getBackgroundInformationEN();

	/**
	 * Sets the background information en of this commitment.
	 *
	 * @param backgroundInformationEN the background information en of this commitment
	 */
	public void setBackgroundInformationEN(String backgroundInformationEN);

	/**
	 * Returns the background information sv of this commitment.
	 *
	 * @return the background information sv of this commitment
	 */
	@AutoEscape
	public String getBackgroundInformationSV();

	/**
	 * Sets the background information sv of this commitment.
	 *
	 * @param backgroundInformationSV the background information sv of this commitment
	 */
	public void setBackgroundInformationSV(String backgroundInformationSV);

	/**
	 * Returns the short description fi of this commitment.
	 *
	 * @return the short description fi of this commitment
	 */
	@AutoEscape
	public String getShortDescriptionFI();

	/**
	 * Sets the short description fi of this commitment.
	 *
	 * @param shortDescriptionFI the short description fi of this commitment
	 */
	public void setShortDescriptionFI(String shortDescriptionFI);

	/**
	 * Returns the short description en of this commitment.
	 *
	 * @return the short description en of this commitment
	 */
	@AutoEscape
	public String getShortDescriptionEN();

	/**
	 * Sets the short description en of this commitment.
	 *
	 * @param shortDescriptionEN the short description en of this commitment
	 */
	public void setShortDescriptionEN(String shortDescriptionEN);

	/**
	 * Returns the short description sv of this commitment.
	 *
	 * @return the short description sv of this commitment
	 */
	@AutoEscape
	public String getShortDescriptionSV();

	/**
	 * Sets the short description sv of this commitment.
	 *
	 * @param shortDescriptionSV the short description sv of this commitment
	 */
	public void setShortDescriptionSV(String shortDescriptionSV);

	/**
	 * Returns the address of this commitment.
	 *
	 * @return the address of this commitment
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this commitment.
	 *
	 * @param address the address of this commitment
	 */
	public void setAddress(String address);

	/**
	 * Returns the longitude of this commitment.
	 *
	 * @return the longitude of this commitment
	 */
	public double getLongitude();

	/**
	 * Sets the longitude of this commitment.
	 *
	 * @param longitude the longitude of this commitment
	 */
	public void setLongitude(double longitude);

	/**
	 * Returns the latitude of this commitment.
	 *
	 * @return the latitude of this commitment
	 */
	public double getLatitude();

	/**
	 * Sets the latitude of this commitment.
	 *
	 * @param latitude the latitude of this commitment
	 */
	public void setLatitude(double latitude);

	/**
	 * Returns the commitment type of this commitment.
	 *
	 * @return the commitment type of this commitment
	 */
	@AutoEscape
	public String getCommitmentType();

	/**
	 * Sets the commitment type of this commitment.
	 *
	 * @param commitmentType the commitment type of this commitment
	 */
	public void setCommitmentType(String commitmentType);

	/**
	 * Returns the status of this commitment.
	 *
	 * @return the status of this commitment
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this commitment.
	 *
	 * @param status the status of this commitment
	 */
	public void setStatus(String status);

	/**
	 * Returns the likes of this commitment.
	 *
	 * @return the likes of this commitment
	 */
	public int getLikes();

	/**
	 * Sets the likes of this commitment.
	 *
	 * @param likes the likes of this commitment
	 */
	public void setLikes(int likes);

	/**
	 * Returns the joined of this commitment.
	 *
	 * @return the joined of this commitment
	 */
	public int getJoined();

	/**
	 * Sets the joined of this commitment.
	 *
	 * @param joined the joined of this commitment
	 */
	public void setJoined(int joined);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Commitment commitment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Commitment> toCacheModel();

	@Override
	public Commitment toEscapedModel();

	@Override
	public Commitment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}