/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fi.weasel.commitment2050.commitmentanalysis.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Report service. Represents a row in the &quot;CA_Report&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.weasel.commitment2050.commitmentanalysis.model.impl.ReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.weasel.commitment2050.commitmentanalysis.model.impl.ReportImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Report
 * @see fi.weasel.commitment2050.commitmentanalysis.model.impl.ReportImpl
 * @see fi.weasel.commitment2050.commitmentanalysis.model.impl.ReportModelImpl
 * @generated
 */
@ProviderType
public interface ReportModel extends BaseModel<Report> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a report model instance should use the {@link Report} interface instead.
	 */

	/**
	 * Returns the primary key of this report.
	 *
	 * @return the primary key of this report
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this report.
	 *
	 * @param primaryKey the primary key of this report
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this report.
	 *
	 * @return the ID of this report
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this report.
	 *
	 * @param id the ID of this report
	 */
	public void setId(String id);

	/**
	 * Returns the report ID of this report.
	 *
	 * @return the report ID of this report
	 */
	@AutoEscape
	public String getReportId();

	/**
	 * Sets the report ID of this report.
	 *
	 * @param reportId the report ID of this report
	 */
	public void setReportId(String reportId);

	/**
	 * Returns the operation ID of this report.
	 *
	 * @return the operation ID of this report
	 */
	@AutoEscape
	public String getOperationId();

	/**
	 * Sets the operation ID of this report.
	 *
	 * @param operationId the operation ID of this report
	 */
	public void setOperationId(String operationId);

	/**
	 * Returns the commitment ID of this report.
	 *
	 * @return the commitment ID of this report
	 */
	@AutoEscape
	public String getCommitmentId();

	/**
	 * Sets the commitment ID of this report.
	 *
	 * @param commitmentId the commitment ID of this report
	 */
	public void setCommitmentId(String commitmentId);

	/**
	 * Returns the created by user ID of this report.
	 *
	 * @return the created by user ID of this report
	 */
	public int getCreatedByUserId();

	/**
	 * Sets the created by user ID of this report.
	 *
	 * @param createdByUserId the created by user ID of this report
	 */
	public void setCreatedByUserId(int createdByUserId);

	/**
	 * Returns the created by user name of this report.
	 *
	 * @return the created by user name of this report
	 */
	@AutoEscape
	public String getCreatedByUserName();

	/**
	 * Sets the created by user name of this report.
	 *
	 * @param createdByUserName the created by user name of this report
	 */
	public void setCreatedByUserName(String createdByUserName);

	/**
	 * Returns the organization name of this report.
	 *
	 * @return the organization name of this report
	 */
	@AutoEscape
	public String getOrganizationName();

	/**
	 * Sets the organization name of this report.
	 *
	 * @param organizationName the organization name of this report
	 */
	public void setOrganizationName(String organizationName);

	/**
	 * Returns the progress of this report.
	 *
	 * @return the progress of this report
	 */
	@AutoEscape
	public String getProgress();

	/**
	 * Sets the progress of this report.
	 *
	 * @param progress the progress of this report
	 */
	public void setProgress(String progress);

	/**
	 * Returns the report start date of this report.
	 *
	 * @return the report start date of this report
	 */
	public Date getReportStartDate();

	/**
	 * Sets the report start date of this report.
	 *
	 * @param reportStartDate the report start date of this report
	 */
	public void setReportStartDate(Date reportStartDate);

	/**
	 * Returns the report end date of this report.
	 *
	 * @return the report end date of this report
	 */
	public Date getReportEndDate();

	/**
	 * Sets the report end date of this report.
	 *
	 * @param reportEndDate the report end date of this report
	 */
	public void setReportEndDate(Date reportEndDate);

	/**
	 * Returns the report status of this report.
	 *
	 * @return the report status of this report
	 */
	public boolean getReportStatus();

	/**
	 * Returns <code>true</code> if this report is report status.
	 *
	 * @return <code>true</code> if this report is report status; <code>false</code> otherwise
	 */
	public boolean isReportStatus();

	/**
	 * Sets whether this report is report status.
	 *
	 * @param reportStatus the report status of this report
	 */
	public void setReportStatus(boolean reportStatus);

	/**
	 * Returns the report text fi of this report.
	 *
	 * @return the report text fi of this report
	 */
	@AutoEscape
	public String getReportTextFI();

	/**
	 * Sets the report text fi of this report.
	 *
	 * @param reportTextFI the report text fi of this report
	 */
	public void setReportTextFI(String reportTextFI);

	/**
	 * Returns the report text sv of this report.
	 *
	 * @return the report text sv of this report
	 */
	@AutoEscape
	public String getReportTextSV();

	/**
	 * Sets the report text sv of this report.
	 *
	 * @param reportTextSV the report text sv of this report
	 */
	public void setReportTextSV(String reportTextSV);

	/**
	 * Returns the report text en of this report.
	 *
	 * @return the report text en of this report
	 */
	@AutoEscape
	public String getReportTextEN();

	/**
	 * Sets the report text en of this report.
	 *
	 * @param reportTextEN the report text en of this report
	 */
	public void setReportTextEN(String reportTextEN);

	/**
	 * Returns the report title fi of this report.
	 *
	 * @return the report title fi of this report
	 */
	@AutoEscape
	public String getReportTitleFI();

	/**
	 * Sets the report title fi of this report.
	 *
	 * @param reportTitleFI the report title fi of this report
	 */
	public void setReportTitleFI(String reportTitleFI);

	/**
	 * Returns the report title sv of this report.
	 *
	 * @return the report title sv of this report
	 */
	@AutoEscape
	public String getReportTitleSV();

	/**
	 * Sets the report title sv of this report.
	 *
	 * @param reportTitleSV the report title sv of this report
	 */
	public void setReportTitleSV(String reportTitleSV);

	/**
	 * Returns the report title en of this report.
	 *
	 * @return the report title en of this report
	 */
	@AutoEscape
	public String getReportTitleEN();

	/**
	 * Sets the report title en of this report.
	 *
	 * @param reportTitleEN the report title en of this report
	 */
	public void setReportTitleEN(String reportTitleEN);

	/**
	 * Returns the status of this report.
	 *
	 * @return the status of this report
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this report.
	 *
	 * @param status the status of this report
	 */
	public void setStatus(String status);

	/**
	 * Returns the version of this report.
	 *
	 * @return the version of this report
	 */
	public double getVersion();

	/**
	 * Sets the version of this report.
	 *
	 * @param version the version of this report
	 */
	public void setVersion(double version);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Report report);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Report> toCacheModel();

	@Override
	public Report toEscapedModel();

	@Override
	public Report toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}